### ISSUE TITLE
can't load object_detection.py

### ISSUE THREAD

**Issue by Nyceane** [gudovskiy/yoloNCS#1]
Hey, I am getting an error loading this.

```
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
[INFO/ForkPoolWorker-1] process shutting down
[DEBUG/ForkPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-1] running the remaining "atexit" finalizers
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[INFO/ForkPoolWorker-1] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (18,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()

```

Let me know if you can help

**Comment by mantoone** [comment]
Looks like you're not getting an image from the webcam. Do you have a camera available at /dev/video0 ?

**Comment by gudovskiy** [comment]
@Nyceane, I agree with @mantoone. Most likely, you have OpenCV installed from pip3 or deb without video support. You may want to install (I personally did this) from sources which is described in OPTION 2 [here](http://milq.github.io/install-opencv-ubuntu-debian/) or other web-sites.

**Comment by Nyceane** [comment]
Hey @gudovskiy 

Thanks for the reply, I've went through the install option 2 and installed opencv using OPTION 2 from milq, which I am able to run the video.py example to make sure that video port is open and running.  I am also able to run the yolo_example.py

Below are full log that's crashing, it doesn't seem have to do with anything with opencv and /dev/video0

Let me know if you can take a look at it.

`python3 object_detection_app.py 
[DEBUG/MainProcess] created semlock with handle 140636040278016
[DEBUG/MainProcess] created semlock with handle 140636040273920
[DEBUG/MainProcess] created semlock with handle 140636040269824
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140636040265728
[DEBUG/MainProcess] created semlock with handle 140636040261632
[DEBUG/MainProcess] created semlock with handle 140636040257536
[DEBUG/MainProcess] Queue._after_fork()
Found stale device, resetting
Device 0 Address: 2 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 2 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 825136 bytes...
Successfully sent 825136 bytes of data in 55.532122 ms (14.170375 MB/s)
Boot successful, device address 2
Found Address: 2 - VID/PID 040e:f63b
done
Booted 2 -> VSC
[DEBUG/MainProcess] created semlock with handle 140636040253440
[DEBUG/MainProcess] created semlock with handle 140636040249344
[DEBUG/MainProcess] created semlock with handle 140636040245248
[DEBUG/MainProcess] created semlock with handle 140636040241152
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[INFO/ForkPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
[INFO/ForkPoolWorker-1] process shutting down
[DEBUG/ForkPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-1] running the remaining "atexit" finalizers
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[INFO/ForkPoolWorker-1] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (18,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()

`

**Comment by Nyceane** [comment]
hey @gudovskiy @mantoone 

Thanks for the response, I have used OPTION 2 and was able to run video.py and I am able to run yolo_example.py.  I don't think there is anything wrong with openCV right now.

I am pasting the full log, can you take a look at it?

The problem seems happening on line 113

 File "object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')


```
python3 object_detection_app.py 
[DEBUG/MainProcess] created semlock with handle 140636040278016
[DEBUG/MainProcess] created semlock with handle 140636040273920
[DEBUG/MainProcess] created semlock with handle 140636040269824
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140636040265728
[DEBUG/MainProcess] created semlock with handle 140636040261632
[DEBUG/MainProcess] created semlock with handle 140636040257536
[DEBUG/MainProcess] Queue._after_fork()
Found stale device, resetting
Device 0 Address: 2 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 2 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 825136 bytes...
Successfully sent 825136 bytes of data in 55.532122 ms (14.170375 MB/s)
Boot successful, device address 2
Found Address: 2 - VID/PID 040e:f63b
done
Booted 2 -> VSC
[DEBUG/MainProcess] created semlock with handle 140636040253440
[DEBUG/MainProcess] created semlock with handle 140636040249344
[DEBUG/MainProcess] created semlock with handle 140636040245248
[DEBUG/MainProcess] created semlock with handle 140636040241152
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[INFO/ForkPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
[INFO/ForkPoolWorker-1] process shutting down
[DEBUG/ForkPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-1] running the remaining "atexit" finalizers
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[INFO/ForkPoolWorker-1] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (18,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()
```

**Comment by gudovskiy** [comment]
@Nyceane could you paste content of frame and try calling cv2.imshow() for it?

**Comment by Nyceane** [comment]
Hey @gudovskiy 

It says when I printed it. 
frame:
None

**Comment by Nyceane** [comment]
@gudovskiy 

Found some issue, I am able to run python video.py fine, but python3 video.py can't find video source.  Let me playing around it a little more.

**Comment by gudovskiy** [comment]
@Nyceane sure. Check whether opencv was installed from pip3 by runnung "pip3 list", you may want to remove pip3 version.

**Comment by Nyceane** [comment]
hey @gudovskiy 

After reinstalling and installing different cameras, i finally got both examples running, but neither of them are finding targets using both YoloTiny and YoloSmall

also, object_detection.py is running at about 1 frame a second with an error on line 73, which is comparing an array of nans (probs) to a float (threshold)

yolo_example is having same problem on line 40, np.array(probs>=threshold

let me know if you ran into same trouble.

![screenshot from 2017-09-13 15-46-23](https://user-images.githubusercontent.com/271430/30404424-7bbb047a-989b-11e7-9d72-aa494f4045b5.png)
![screenshot from 2017-09-13 15-48-32](https://user-images.githubusercontent.com/271430/30404423-7bb7cab2-989b-11e7-8940-9ff3b0717632.png)

**Comment by gudovskiy** [comment]
@Nyceane looks like you are using YOLO small which is not producing proper results due to some reason. Only YOLO tiny is working now.

**Comment by Nyceane** [comment]
@gudovskiy yoloTiny is not producing any results either in both cases, no errors tho

![object](https://user-images.githubusercontent.com/271430/30412209-aecad488-98ca-11e7-98b9-ea63ead9ed85.png)
![yolotiny](https://user-images.githubusercontent.com/271430/30412210-aede5d8c-98ca-11e7-9cad-37a17a370b60.png)

**Comment by gudovskiy** [comment]
@Nyceane strange, mine is working even on Raspberry Pi.

**Comment by pascalpm** [comment]
Make sure the caffemodel and the prototxt files have the same name! In this case yolo_tiny.caffemodel and yolo_tiny.prototxt when you compile (python3 ./mvNCCompile.pyc data/yolo_tiny.prototxt -s 12).

**Comment by Nyceane** [comment]
@pascalpm, they are same name

**Comment by ashwinnair14** [comment]
@gudovskiy @Nyceane At what FPS does it run ??

**Comment by gudovskiy** [comment]
@ashwinnair14 ~5-6 FPS with USB3

**Comment by value56** [comment]
@Nyceane Did you solve your problem? I meet the same problem, python3 video.py can't find video source. How did you solve this problem?

**Comment by thepaintedsnipe** [comment]
Hitting the exact same error
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "py_examples/object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[INFO/ForkPoolWorker-1] process exiting with exitcode 1

**Comment by thepaintedsnipe** [comment]
Hi,
1. pip3 list | grep opencv
this showed up some opencv entries which I removed

2. then installed the opencv from sources as described in the link you share earlier 
http://milq.github.io/install-opencv-ubuntu-debian/

Now, got it to work
On NCS, I get around 4-5 FPS. I guess this is what every one else is getting too?

Detection error is pretty high.
But your application is a very good started point for those who want to get started. 
Improving detection error is just a matter of better training. 

Thanks for your effort in putting together this project and sharing with every one.

**Comment by gudovskiy** [comment]
@thepaintedsnipe thank you. other guy solved the same way https://github.com/gudovskiy/yoloNCS/issues/4

**Comment by gotibhai** [comment]
@gudovskiy Do you have the file for the reading the video stream from a PiCamera instead of cv2.VideoCapture? Or should the videoCapture work on Pi as well using the camera module on its own?

**Comment by gudovskiy** [comment]
@gotibhai as I remember, PiCamera also worked using openCV. I tried its own driver and didn't notice any difference. So, both should work.

**Comment by HEUzhouhanwen** [comment]
I met the same error like you ,I cannot get the bounding box on RPI 3 too,I‘m sure there is no problem with the program，because it works well on pc with the same graph.
  I think it's NCS not work normally result in this error,I try the inception,it return error,But the hello_ncs_py works well.

**Comment by gotibhai** [comment]
@gudovskiy Did the code work as well on the pi as it did on a development host? It's not working well on the pi for me. Even yolo_example.py is not working on the pi. 

@HEUzhouhanwen Yeah, My error is a little different. I got it working on the pi hooked on to the monitor. I modified the file a bit to use PiCamera module. Everything worked fine there but then I hooked up an adafruit PITFT 2'4 screen to the pi to show the results there and it doesn't work. The boxes are not showing properly. I'm always getting this same box with 0.05 probability.

**Comment by gudovskiy** [comment]
@gotibhai for PI the difficulty was to install OpenCV. Apart from that everything should work fine but slower due to USB2.0

**Comment by gotibhai** [comment]
@gudovskiy Ahh that sucks. OpenCV worked me but it's not predicting properly at all.

**Comment by gotibhai** [comment]
@Nyceane did you manage to solve the problem of it not predicting?

**Comment by HEUzhouhanwen** [comment]
@Nyceane  I solve the problem ,I try all the way to find the error but failed.Today I notice the pc(it can get the bounding box) use the previous version of api, the I install the previous NCS api,so guess what ? I get the bounding box!!!! 
![image](https://user-images.githubusercontent.com/34428987/34071172-5828903e-e2ad-11e7-9373-deedb2e706e5.png)

**Comment by mashrin** [comment]
I am still getting this error.


[DEBUG/MainProcess] created semlock with handle 140640753795072
[DEBUG/MainProcess] created semlock with handle 140640753790976
[DEBUG/MainProcess] created semlock with handle 140640753786880
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140640753782784
[DEBUG/MainProcess] created semlock with handle 140640753778688
[DEBUG/MainProcess] created semlock with handle 140640753774592
[DEBUG/MainProcess] Queue._after_fork()
Device 0 Address: 2 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 2 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 865212 bytes...
Successfully sent 865212 bytes of data in 75.316412 ms (10.955520 MB/s)
Boot successful, device address 2
Found Address: 2 - VID/PID 03e7:f63b
done
Booted 2 -> VSC
[DEBUG/MainProcess] created semlock with handle 140640753770496
[DEBUG/MainProcess] created semlock with handle 140640753766400
[DEBUG/MainProcess] created semlock with handle 140640753762304
[DEBUG/MainProcess] created semlock with handle 140640753758208
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[INFO/ForkPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
[INFO/ForkPoolWorker-1] process shutting down
[DEBUG/ForkPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-1] running the remaining "atexit" finalizers
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "py_examples/object_detection_app.py", line 113, in worker
    graph.LoadTensor(resize(frame/255.0,dim,1)[:,:,(2,1,0)].astype(np.float16), 'user object')
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[INFO/ForkPoolWorker-1] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (18,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()
^C[INFO/ForkPoolWorker-2] process shutting down
[INFO/ForkPoolWorker-3] process shutting down
[DEBUG/ForkPoolWorker-2] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-3] running all "atexit" finalizers with priority >= 0
Traceback (most recent call last):
[DEBUG/ForkPoolWorker-2] running the remaining "atexit" finalizers
Process ForkPoolWorker-2:
[DEBUG/ForkPoolWorker-3] running the remaining "atexit" finalizers
  File "py_examples/object_detection_app.py", line 170, in <module>
Process ForkPoolWorker-3:
    (img, results, img_width, img_height) = output_q.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "py_examples/object_detection_app.py", line 112, in worker
    frame = input_q.get()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "py_examples/object_detection_app.py", line 112, in worker
    frame = input_q.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
KeyboardInterrupt
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
[INFO/ForkPoolWorker-3] process exiting with exitcode 1
[INFO/ForkPoolWorker-2] process exiting with exitcode 1
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
[DEBUG/MainProcess] cleaning up worker 1
[Level 5/MainProcess] finalizer calling <built-in function close> with args (18,) and kwargs {}
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (19,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-4] Queue._after_fork()
[DEBUG/ForkPoolWorker-4] Queue._after_fork()
[INFO/ForkPoolWorker-4] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-5] Queue._after_fork()
[DEBUG/ForkPoolWorker-5] Queue._after_fork()
[INFO/ForkPoolWorker-5] child process calling self.run()


Can anyone kindly help me out with this.

Thanks!
