### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by SantiMancini** [gudovskiy/yoloNCS#10]
Hello,
First of all, thank you for the project. I already installed the project and compiled everything. The problem is when I try to run 'python3 py_examples/yolo_example.py images/dog.jpg' I get the following error:

> Device 0 Address: 3 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 3 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 865212 bytes...
Successfully sent 865212 bytes of data in 457.894553 ms (1.802010 MB/s)
Boot successful, device address 3
Found Address: 3 - VID/PID 03e7:f63b
done
Booted 3 -> VSC
Traceback (most recent call last):
  File "py_examples/yolo_example.py", line 126, in <module>
    graph = device.AllocateGraph(blob)
  File "/usr/local/lib/python3.5/dist-packages/mvnc/mvncapi.py", line 201, in AllocateGraph
    raise Exception(Status(status))
Exception: mvncStatus.ERROR

Any suggestions? I do have the 'graph' file in the main folder. Thanks again!

**Comment by gudovskiy** [comment]
@SantiMancini can you run other examples from Movidius?
