### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by sctang25** [gudovskiy/yoloNCS#11]
Facing error during compilation. Any idea on this? 

Thanks for the help in advance.

mvNCCompile v02.00, Copyright @ Movidius Ltd 2016

**_Traceback (most recent call last):
  File "/usr/local/bin/mvNCCompile", line 118, in <module>
    create_graph(args.network, args.inputnode, args.outputnode, args.outfile, args.nshaves, args.inputsize, args.weights)
  File "/usr/local/bin/mvNCCompile", line 101, in create_graph
    net = parse_caffe(args, myriad_config)
  File "/usr/local/bin/ncsdk/Controllers/CaffeParser.py", line 365, in parse_caffe
    if layers[0].type == 'Input':
IndexError: list index out of range_**

**Comment by gudovskiy** [comment]
@sctang25 hmm which version of NCS SDK do you use? Could you compile other networks?

**Comment by sctang25** [comment]
NCS SDK v1.12.
Other network compilation is ok.
