### ISSUE TITLE
py_examples error

### ISSUE THREAD

**Issue by burakipekk** [gudovskiy/yoloNCS#13]
Hi Everyone 
I am getting error like below , could you please help me? Camera light is on and I installed OPENCV that was explained in 'http://milq.github.io/install-opencv-ubuntu-debian/' with OPTION 2. All examples work fine but I am still getting error like below. (ValueError: cannot reshape array of size 16922 into shape (7,7,2,4) this line looks like in trouble but I dont know how I can solve.)

[DEBUG/MainProcess] created semlock with handle 140701902925824
[DEBUG/MainProcess] created semlock with handle 140701902921728
[DEBUG/MainProcess] created semlock with handle 140701902917632
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140701902913536
[DEBUG/MainProcess] created semlock with handle 140701902909440
[DEBUG/MainProcess] created semlock with handle 140701902905344
[DEBUG/MainProcess] Queue._after_fork()
Found stale device, resetting
Device 0 Address: 1.3.3 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 1.3.3 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 865724 bytes...
Successfully sent 865724 bytes of data in 214.364144 ms (3.851478 MB/s)
Boot successful, device address 1.3.3
Found Address: 1.3.3 - VID/PID 03e7:f63b
done
Booted 1.3.3 -> VSC
[DEBUG/MainProcess] created semlock with handle 140701902901248
[DEBUG/MainProcess] created semlock with handle 140701902897152
[DEBUG/MainProcess] created semlock with handle 140701902893056
[DEBUG/MainProcess] created semlock with handle 140701902888960
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[INFO/ForkPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
/usr/local/lib/python3.5/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
[INFO/ForkPoolWorker-1] process shutting down
[DEBUG/ForkPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-1] running the remaining "atexit" finalizers
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "py_examples/object_detection_app.py", line 115, in worker
    results = interpret_output(out.astype(np.float32), frame.shape[1], frame.shape[0])
  File "py_examples/object_detection_app.py", line 55, in interpret_output
    boxes = (np.reshape(output[1078:],(7,7,2,4)))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 16922 into shape (7,7,2,4)
[INFO/ForkPoolWorker-1] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 0
[Level 5/MainProcess] finalizer calling <built-in function close> with args (19,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()

**Comment by alexnf333** [comment]
Hello burakipekk, 
I'm having the same problem, could you solve it? Or do you have any idea of how to?

Thanks in advance!
Best regards.
