### ISSUE TITLE
Can run sample for NCSv1.12

### ISSUE THREAD

**Issue by masterchop** [gudovskiy/yoloNCS#16]
pi@raspberrypi:~/YoloV2NCS-1.0 $ python3 detectionExample/Main.py 
Traceback (most recent call last):
  File "detectionExample/Main.py", line 5, in <module>
    from ObjectWrapper import *
  File "/home/pi/YoloV2NCS-1.0/detectionExample/ObjectWrapper.py", line 1, in <module>
    ﻿from libpydetector import YoloDetector
ImportError: /home/pi/YoloV2NCS-1.0/detectionExample/libpydetector.so: wrong ELF class: ELFCLASS64

I compiled it on another box a move the files, created the  lync

**Comment by masterchop** [comment]
works on the VM i compile it, i cant compile it on pi as it doesnt ahve boost library

**Comment by devil-V-white** [comment]
> works on the VM i compile it, i cant compile it on pi as it doesnt ahve boost library

**Comment by devil-V-white** [comment]
Can u tell how to resolve it exactly...
