### ISSUE TITLE
can you share instructions for ncsdf 1.09 release? 

### ISSUE THREAD

**Issue by YingUK** [gudovskiy/yoloNCS#2]
Hi, 

I just bought the Movidius stick and installed ncsdk 1.09 release. Seems the structure has changed a lot.  Command line for mvNCCompile is different, and i cannot find the directory for ncapi/networks/YoloTiny/ . Could you please provide suggestions that how I can run tiny yolo in ncsdk1.09 please?

**Comment by gudovskiy** [comment]
@YingHou update code. Now it should be even easier to deploy.

**Comment by YingUK** [comment]
@gudovskiy, thank you so much for your quick response! I see below error message. 
```
py_examples/yolo_example.py:115: DeprecationWarning: "LOGLEVEL" is deprecated. Please use "LOG_LEVEL"!
  mvnc.SetGlobalOption(mvnc.GlobalOption.LOGLEVEL, 2)
Device 0 Address: 2 - VID/PID 03e7:2150
Starting wait for connect with 2000ms timeout
Found Address: 2 - VID/PID 03e7:2150
Found EP 0x81 : max packet size is 512 bytes
Found EP 0x01 : max packet size is 512 bytes
Found and opened device
Performing bulk write of 813376 bytes...
Successfully sent 813376 bytes of data in 310.401178 ms (2.499010 MB/s)
Boot successful, device address 2
Device 0 Address: 1 - VID/PID 040e:f63b
Found Address: 1 - VID/PID 040e:f63b
done
Booted 1 -> VSC
py_examples/yolo_example.py:122: DeprecationWarning: "OPTIMISATIONLIST" is deprecated. Please use "OPTIMISATION_LIST"!
  opt = device.GetDeviceOption(mvnc.DeviceOption.OPTIMISATIONLIST)
Traceback (most recent call last):
  File "py_examples/yolo_example.py", line 122, in <module>
    opt = device.GetDeviceOption(mvnc.DeviceOption.OPTIMISATIONLIST)
  File "/usr/local/lib/python2.7/dist-packages/mvnc/mvncapi.py", line 190, in GetDeviceOption
    end = ss.find(0)
TypeError: expected a string or other character buffer object
```
I'm running Movidius in Ubuntu VirtualBox, is this causing this error? 
Thank you so much for your help!

**Comment by YingUK** [comment]
I comment line 122 in yolo_example.py, all working now.  Thanks!

**Comment by gudovskiy** [comment]
@YingHou oh yeah, they renamed those arguments.
